-- Roteiros iniciais do treinamento do call center (situação · o cliente diz · resposta sugerida · no sistema · evitar)
insert into public.roteiros (categoria, situacao, cliente_diz, resposta, no_sistema, evitar, autor_nome) values
('entrega','Móvel disponível no depósito — agendar entrega',
 'Oi, me disseram que meu guarda-roupa já chegou. Quando vocês entregam?',
 'Que ótima notícia! Deixa eu confirmar aqui… Sim, o seu guarda-roupa está disponível no nosso depósito. Tenho disponibilidade na terça ou na quinta, de manhã ou à tarde. Qual fica melhor para o senhor? … Perfeito, fica agendado para quinta de manhã. Alguém maior de idade precisa estar no local para receber. Posso confirmar o endereço?',
 'Confira a disponibilidade no Tático, lance a entrega, abra (ou use) a Solicitação de entrega e clique em "Colocar para entrega (Tático)". Anote data e período combinados.',
 'Agendar sem conferir no Tático. Prometer horário exato quando a rota é por período.','Treinamento inicial'),
('entrega','Cliente quer antecipar a entrega',
 'Preciso receber antes, vou mudar na sexta!',
 'Entendo, mudança já é corrida. Vou verificar se consigo encaixar antes de sexta. Se não houver vaga, já deixo o senhor como prioridade caso abra horário e te ligo até amanhã às 12h com a resposta.',
 'Registre na anotação o motivo e a data-limite do cliente. Marque urgente se a data for próxima.',
 '"Não tem como." sem verificar.','Treinamento inicial'),
('atraso','Prazo de entrega vencido',
 'O prazo era dia 10 e até agora nada. Vocês estão me enrolando!',
 'O senhor tem toda razão em cobrar: o prazo era dia 10 e ainda não entregamos. Peço desculpas. Estou vendo aqui que o pedido está com a fábrica. Vou cobrar o representante agora e te ligo até amanhã às 17h com a nova data, independente da resposta.',
 'Abra a ficha, use "WhatsApp do representante" para cobrar, registre na anotação a data do retorno combinada. Se não houver chamado, abra "Prazo de fábrica".',
 'Culpar a fábrica. "Não depende de mim."','Treinamento inicial'),
('atraso','Cliente já ligou várias vezes',
 'Já é a quinta vez que eu ligo e ninguém resolve nada!',
 'Peço desculpas por o senhor ter precisado ligar tantas vezes, isso não deveria acontecer. Meu nome é ___ e a partir de agora eu acompanho o seu caso pessoalmente. Vou ler o que está registrado: … O próximo passo é ___ e eu te ligo até ___ com a posição, mesmo que ainda não esteja resolvido.',
 'Marque urgente, registre "3ª ligação ou mais" na anotação e avise a Supervisão. Cumpra o retorno antes do prazo.',
 'Pedir que ele explique tudo de novo sem ler o histórico antes.','Treinamento inicial'),
('montagem','Montador não apareceu',
 'Fiquei a manhã inteira esperando e o montador não veio!',
 'Sinto muito, o senhor se organizou e ficou esperando, isso é muito chato. Vou falar agora com a Montagem para reagendar com prioridade e confirmar o motivo. Te retorno ainda hoje até as 17h com a nova data.',
 'Marque urgente no chamado de montagem e registre o ocorrido. Se não houver chamado, abra "Solicitação de montagem" com a observação "montador não compareceu em __/__".',
 'Dar desculpa pelo montador ("deve ter tido imprevisto").','Treinamento inicial'),
('montagem','Montagem ficou mal feita (planejado)',
 'A porta ficou torta e tem um painel solto.',
 'Obrigado por avisar, vamos resolver. Consegue me mandar fotos pelo WhatsApp mostrando a porta e o painel? Vou registrar para a nossa equipe de pós-venda analisar e programar o retorno do montador. Em até 2 dias úteis entramos em contato com a solução.',
 'Abra "Pós-venda projetados": quem acionou = cliente, peça afetada, relato com as palavras dele e as fotos.',
 'Dizer que o montador errou antes da análise.','Treinamento inicial'),
('defeito','Móvel chegou riscado ou quebrado',
 'O móvel chegou todo riscado, não aceito isso!',
 'O senhor está certo em não aceitar, o móvel precisa chegar perfeito. Vou registrar agora com fotos para resolvermos: pode me mandar as imagens do risco e da etiqueta da caixa? A equipe analisa e te retorna em até 2 dias úteis com a solução.',
 'Planejado: "Pós-venda projetados". Outros móveis: "Solicitação de assistência" ou "vistoria". Anexe as fotos na ficha.',
 'Discutir se o risco foi no transporte ou na montagem com o cliente.','Treinamento inicial'),
('defeito','Cliente quer móvel novo, não reposição',
 'Não quero peça, quero outro móvel novo!',
 'Entendo que o senhor quer ter certeza de que vai ficar perfeito. Vou registrar o seu pedido de troca junto com a análise do defeito, e a decisão sai com a gerência. Te dou a posição até ___.',
 'Registre o pedido de troca entre aspas na anotação e avise a Supervisão. Não prometa troca.',
 '"Não fazemos troca." ou prometer troca sem autorização.','Treinamento inicial'),
('cancelamento','Cliente quer cancelar a compra',
 'Quero cancelar tudo, desisti!',
 'Posso te ajudar com isso. Antes, me conta o que aconteceu para o senhor pensar em cancelar? … Entendi, é o prazo. Deixa eu ver o que consigo fazer por ele agora… Se ainda assim o senhor quiser cancelar, eu registro e a gerência te retorna até ___.',
 'Registre o motivo e o pedido de cancelamento na anotação. Avise a Supervisão no mesmo dia.',
 'Aceitar ou negar o cancelamento por conta própria.','Treinamento inicial'),
('cancelamento','Cliente quer o dinheiro de volta',
 'Quero meu dinheiro de volta!',
 'Entendo. Vou levar o seu pedido para a gerência hoje mesmo, com todo o histórico, e te retorno até ___ com a resposta.',
 'Registre na anotação e avise a Supervisão. Marque urgente.',
 'Prometer estorno ou informar prazos de estorno sem autorização.','Treinamento inicial'),
('reclamacao_externa','Cliente ameaça o Reclame Aqui',
 'Se não resolverem hoje eu vou colocar no Reclame Aqui!',
 'Entendo, e o senhor tem esse direito. Eu quero resolver antes disso: me dá essa chance? Estou vendo aqui que ___. O que vou fazer agora é ___, e te ligo até ___ com a posição.',
 'Marque urgente. Na anotação escreva a frase do cliente entre aspas. Avise a Supervisão no mesmo dia.',
 '"Pode colocar onde quiser." Discutir ou se defender.','Treinamento inicial'),
('reclamacao_externa','Cliente ameaça o Procon',
 'Vou no Procon amanhã!',
 'Compreendo a sua insatisfação. Antes disso, deixa eu te mostrar o que está registrado e o que já estamos fazendo: ___. Meu compromisso é te ligar até ___ com a solução.',
 'Marque urgente, registre a frase entre aspas, avise a Supervisão. Nada de orientação jurídica ao telefone.',
 'Falar de direitos, leis ou prazos legais. Ironia.','Treinamento inicial'),
('reclamacao_externa','Cliente vai postar ou já postou nas redes sociais',
 'Vou postar no Instagram o que vocês fizeram comigo.',
 'Eu entendo a sua chateação. Prefiro resolver direto com o senhor: o que resolveria o seu problema hoje? … Combinado: vou ___ e te retorno até ___.',
 'Se já foi publicado, peça o link ou print e passe para a Supervisão. Marque urgente.',
 'Responder a publicação em nome da loja.','Treinamento inicial'),
('reclamacao_externa','Cliente quer falar com o gerente',
 'Quero falar com o gerente, não com você!',
 'Claro, vou registrar tudo agora para o gerente já receber o seu caso completo. Enquanto isso, deixa eu ver o que eu já consigo resolver para o senhor não ficar esperando.',
 'Registre e avise a Supervisão. Informe ao cliente quando vai haver o retorno.',
 '"O gerente não atende." ou transferir sem registrar o caso.','Treinamento inicial'),
('retorno','Retorno sem novidade',
 '(Você liga para o cliente, mas ainda não tem a data.)',
 'Oi, ___, aqui é ___ da Aliança Móveis. Combinei de te dar retorno hoje: ainda não tenho a data da fábrica, mas cobrei de novo agora de manhã. Volto a te ligar na quinta com a posição.',
 'Registre a ligação na anotação, mesmo sem novidade.',
 'Não ligar porque "não tem novidade".','Treinamento inicial'),
('geral','Cliente muito exaltado',
 '(Cliente gritando, sem deixar falar.)',
 'Deixe o cliente terminar. Depois, em tom calmo: "O senhor está certo em estar chateado. Quero te ajudar. Posso te fazer duas perguntas para entender e resolver?"',
 'Registre o essencial na anotação. Se não houver acordo, avise a Supervisão.',
 '"Calma." Levantar o tom de voz. Desligar.','Treinamento inicial'),
('geral','"Vocês só enrolam"',
 'Vocês só sabem enrolar!',
 'Entendo a sua frustração. Vou te passar exatamente o que está registrado, com datas: ___. E o próximo passo é ___, até ___.',
 'Leia o histórico da ficha com o cliente na linha.',
 'Rebater ou justificar a empresa.','Treinamento inicial');
